/**
 * Auto-generated by openapi-typescript from the Django Ninja OpenAPI schema.
 *
 * DO NOT EDIT MANUALLY — regenerate with:
 *   pnpm generate-types
 *
 * Requires the Django backend to be running:
 *   cd backend && python manage.py runserver
 */

export interface paths {
  "/api/auth/pair": {
    post: operations["obtain_token_api_auth_pair_post"];
  };
  "/api/auth/refresh": {
    post: operations["refresh_token_api_auth_refresh_post"];
  };
  "/api/auth/verify": {
    post: operations["verify_token_api_auth_verify_post"];
  };
  "/api/items/": {
    get: operations["list_items_api_items__get"];
    post: operations["create_item_api_items__post"];
  };
  "/api/items/{item_id}": {
    get: operations["get_item_api_items__item_id__get"];
    patch: operations["update_item_api_items__item_id__patch"];
    delete: operations["delete_item_api_items__item_id__delete"];
  };
}

export interface components {
  schemas: {
    ItemIn: {
      title: string;
      description?: string;
      completed?: boolean;
    };
    ItemOut: {
      id: number;
      title: string;
      description: string;
      completed: boolean;
      owner_id: number;
      created_at: string;
      updated_at: string;
    };
    MessageOut: {
      message: string;
    };
    TokenObtainPairInput: {
      username: string;
      password: string;
    };
    TokenObtainPairOutput: {
      access: string;
      refresh: string;
    };
    TokenRefreshInput: {
      refresh: string;
    };
    TokenRefreshOutput: {
      access: string;
    };
    TokenVerifyInput: {
      token: string;
    };
  };
}

export interface operations {
  obtain_token_api_auth_pair_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenObtainPairInput"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenObtainPairOutput"];
        };
      };
    };
  };
  refresh_token_api_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshInput"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefreshOutput"];
        };
      };
    };
  };
  verify_token_api_auth_verify_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenVerifyInput"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  list_items_api_items__get: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ItemOut"][];
        };
      };
      401: {
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  create_item_api_items__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemIn"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      401: {
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  get_item_api_items__item_id__get: {
    parameters: {
      path: { item_id: number };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      404: {
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  update_item_api_items__item_id__patch: {
    parameters: {
      path: { item_id: number };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemIn"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ItemOut"];
        };
      };
      401: {
        content: {
          "application/json": { detail: string };
        };
      };
      404: {
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
  delete_item_api_items__item_id__delete: {
    parameters: {
      path: { item_id: number };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MessageOut"];
        };
      };
      401: {
        content: {
          "application/json": { detail: string };
        };
      };
      404: {
        content: {
          "application/json": { detail: string };
        };
      };
    };
  };
}
